config/routes.rb
HireYoungTest::Application.routes.draw do
  resources :users
  resources :visitors
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/visitor', to: 'static_pages#create', via: 'post'
  root 'static_pages#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	validates :name, presence: true, length: { maximum: 50 }
  validates :country, presence: true, length: { maximum: 50 }
  validates :city, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}
	has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
	before_save { self.email = email.downcase }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if signed_in? 
      redirect_to(current_user)
    end
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Try again!' # Not quite right!
      render 'new'
  	end
  end

  def destroy
  	sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
	@visitor = Visitor.new()
  end
  def create
    @visitor = Visitor.new(visitor_params)  
    @visitor.save
    render :nothing => true
  end
  private
    def visitor_params
      params.require(:visitor).permit(:email)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :signed_in_user, only: [:show,:edit, :update]
	before_action :correct_user,   only: [:show,:edit, :update]
  def create
    @user = User.new(user_params)  
    if @user.save
      sign_in @user
      flash[:success] = "Thank you for registration. We are glad having your here and work hard to help you with getting first job. No worries, you will get a text when everything is ready."
      redirect_to @user
    else
    	flash[:error] = "Try again! Failed fields are marked with x"
      render 'new'
    end
  end
  
  def new
    @user = User.new
    if signed_in? 
      redirect_to(current_user)
    end
  end

  def show
  	@user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :country, :city)
    end
  def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
  end
  def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end
  def current_user=(user)
    @current_user = user
  end
  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  def current_user?(user)
    user == current_user
  end
  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>

  </small>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
     
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HireYoung</title>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,500' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
    	<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/index.html.erb
<div id="loader-wrapper">
    <div id="loader"></div>
    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>
</div>
<div class="t-toolbar">
	<div class="t-toolbar-logo">
		<%= image_tag("logo.png", :alt => "logo",:class => "t-logo -small") %>

	</div>
	<div class="t-toolbar-menu">
		<a class="t-toolbar-el job-seek">Jobseeker</a>
		<a class="t-toolbar-el company-seek">Company</a>
		<a class="t-toolbar-el contact-seek">Contact</a>
		<a class="t-toolbar-el -log t-modal-caller">Log in</a>
	</div>
</div>
<div class="t-modal">
    <div class="t-modal__inner">
        <a class="t-modal__text">We are launching soon</a>
        <a class="t-modal__text">Leave email and we will let you know when everything is ready</a>
        <%= form_for @visitor, :remote => true, as: :visitor, url: '/visitor' do |f| %>
        <div class="t-modal__row">
            <div class="t-modal__row-el">
                <%= f.text_field :email, class: 't-modal__input'%>
            </div>
            <div class="t-modal__row-el t-modal-caller">
                <%= submit_tag "Continue", class: "t-modal__submit t-button -small -white" %>
            </div>
        </div>
        <% end %>
    </div>
    

</div>


<div class="t-blur-all">
<div id="fullpage">
	<!-- OVERVIEW START -->
    <div class="section s-1">
    	<div class="t-overview">
    		<div class="t-overview__header">
    			<a class="t-header -first">Find your first job or internship for free</a>
    		</div>
    		<a class="t-overview__button t-button -white -big job-seek">
    			<span class="t-button__text">For job seekers</span>
    		</a>
    		<a class="t-overview__button t-button -white -big company-seek">
    			<span class="t-button__text">For companies</span>
    		</a>
    	</div>

			<%= image_tag("bottom_picture.png", :alt => "logo",:class => "t-picture -bottom -main") %>

    </div>
    <!-- OVERVIEW END -->


    <!-- FEATURED1 START -->
    <div class="section s-2">

    	<div class="t-featured">
    		<div class="t-featured__row">
    			<div class="t-featured__row-item">
    				<div class="t-featured__icon"><%= image_tag("skills.png", :alt => "logo",:class => "t-help__icon -1") %></div>
    				<div class="t-featured__description">
    					Showcase your skills instead of work experience
    				</div>
    			</div>
    			<div class="t-featured__row-item">
    				<div class="t-featured__icon"><%= image_tag("find.png", :alt => "logo",:class => "t-help__icon -1")%></div>
    				<div class="t-featured__description">
    					Find job or internship that really suits you
    				</div>
    			</div>
    			<div class="t-featured__row-item">
    				<div class="t-featured__icon"><%= image_tag("phone.png", :alt => "logo",:class => "t-help__icon -1") %></div>
    				<div class="t-featured__description">
    					Stay updated with relevant positions and events
    				</div>
    			</div>
    		</div>
    		<a class="t-featured__button t-button -hollow -big t-modal-caller">
    			<span class="t-button__text">Try now for free</span>
    		</a>
    	</div>
    </div>
    <!-- FEATURED1 END -->

    <!-- REGISTER START -->
    <div class="section s-3">
    	<div class="t-register">
    		<div class="t-register__header">
    			<a class="t-header -second">Create account in less than 5 minutes and start your career path</a>
    		</div>
    	<!--	<div class="t-register__row">
    			<div class="t-register__row-item">
					<div id="dd1" class="t-dropdown-wrapper" tabindex="1">
						<a class="t-dropdown__text">STUDENT</a>
						<a class="t-dropdown__title">I'm</a>
						<ul class="t-dropdown">
							<li><a href="#"><i class="icon-envelope icon-large"></i>STUDENT</a></li>
							<li><a href="#"><i class="icon-truck icon-large"></i>GRADUATE</a></li>
						</ul>
					</div>
    			</div>
    			<div class="t-register__row-item">


    					<div id="dd1" class="t-dropdown-wrapper" tabindex="1">
    						<a class="t-dropdown__text">PART-TIME</a>
							<a class="t-dropdown__title">looking for</a>
							<ul class="t-dropdown">
								<li><a href="#"><i class="icon-envelope icon-large"></i>PART-TIME</a></li>
								<li><a href="#"><i class="icon-truck icon-large"></i>FULL-TIME</a></li>
							</ul>
						</div>

    			</div>
    			<div class="t-register__row-item">

    					<div id="dd3" class="t-dropdown-wrapper" tabindex="3">
							<a class="t-dropdown__text">JOB</a>
							<ul class="t-dropdown">
								<li><a href="#"><i class="icon-envelope icon-large"></i>JOB</a></li>
								<li><a href="#"><i class="icon-truck icon-large"></i>INTERNSHIP</a></li>
							</ul>
						</div>

    			</div>
    			<div class="t-register__row-item">
    				<div class="t-button -big -white">
					Continue
				</div>
    			</div>
    		</div>-->
    		<a class="t-register__button t-button -big -white t-modal-caller">
    			<span class="t-button__text">Continue</span>
    		</a>
    	</div>


		<%= image_tag("table.png", :alt => "logo",:class => "t-picture -bottom -register") %>
   	</div>


   	<!-- FEATURED2 START -->
    <div class="section s-4">
    	<div class="t-featured">
    		<div class="t-featured__row">
    			<div class="t-featured__row-item">
    				<div class="t-featured__icon"><%= image_tag("tools.png", :alt => "logo",:class => "t-help__icon -2") %></div>
    				<div class="t-featured__description">
    					Find workers with skills you need
    				</div>
    			</div>
    			<div class="t-featured__row-item">
    				<div class="t-featured__icon"><%= image_tag("contact.png", :alt => "logo",:class => "t-help__icon -2")%></div>
    				<div class="t-featured__description">
    					Use help of machine learning and psychology tests
    				</div>
    			</div>
    			<div class="t-featured__row-item">
    				<div class="t-featured__icon"><%= image_tag("money.png", :alt => "logo",:class => "t-help__icon -2") %></div>
    				<div class="t-featured__description">
    					Save your money and time
    				</div>
    			</div>
    		</div>
    		<a class="t-featured__button t-button -hollow -big t-modal-caller">
    			<span class="t-button__text">Go for it</span>
    		</a>
    		<a class="t-featured__button t-button -hollow -big t-modal-caller">
    			<span class="t-button__text">Check pricing</span>
    		</a>
    	</div>
    </div>
    <!-- FEATURED2 END-->

    <!-- CONTACT START -->
    <div class="section s-5">

    	<div class="t-contact">
    		<div class="t-contact__header">
    			<a class="t-header -first">Join now and get 3 month of premium support for free</a>
    		</div>
    		<a class="t-contact__button t-button -blue -big t-modal-caller">
    			<span class="t-button__text">Sign up</span>
    		</a>
    		<a class="t-contact__button t-button -white -big t-modal-caller">
    			<span class="t-button__text">Read more</span>
    		</a>
    	</div>

		<div id="over">
			<%= image_tag("company.png", :alt => "company",:class => "t-picture -bottom -register") %>
		</div> 
	</div>
	<!-- CONTACT END -->


	<!-- FEEDBACK START -->
	<div class="section s-6">
		<div class="t-feedback">
    		<div class="t-feedback__header">
    			<a class="t-header -first">Connect with us to ask any question or follow the news</a>
    		</div>
    		<a href="https://www.facebook.com/hireyoung/" class="t-contact__button t-button -social">
    			<%= image_tag("facebook.png", :alt => "company",:class => "t-button -social") %>
    		</a>
    		<a href="https://twitter.com/hire_young" class="t-contact__button t-button -social">
    			<%= image_tag("twitter.png", :alt => "company",:class => "t-button -social") %>
    		</a>
    	</div>
    	<%= image_tag("feed.png", :alt => "logo",:class => "t-picture -bottom -feed") %>
    </div>
    <!-- FEEDBACK END -->
</div>
</div>





<script>
$(window).bind("load", function() {
	var $bottomPictureMain=$(".t-picture.-bottom.-main");
	$bottomPictureMain.css("bottom",-700);
	var $menu=$('#fp-nav.right');
	$menu.css('right',-683);
	var $toolbar=$('.t-toolbar');
	$toolbar.css("top",-700);
	
	 $('body').addClass('loaded');
	setTimeout(function(){
		$menu.animate({right:"17"},{ duration: 900, queue: false });
   		$bottomPictureMain.animate({bottom:"0"},{ duration: 1000, queue: false })
   		$toolbar.animate({top:"0"},{ duration: 900, queue: false })
   		
    },600);

});
$(document).ready(function() {

	

  	//$bottomPictureMain.css("opacity",1);


    $('#fullpage').fullpage({
    	onLeave: function(index, nextIndex, direction){
            var leavingSection = $(this);

            var $firstRow=$(".t-help__icon.-1");
            var $secondRow=$(".t-help__icon.-2");
            var $menu=$("#fp-nav ul li a span");
            if(nextIndex==1)
            	$menu.css("background","#50bdc6");

            else if(nextIndex==2){
            	$menu.css("background","#fff");
                if($firstRow.first().height()!=100)
                	$firstRow.animate({height: "100"},600);
            }
            else if(nextIndex==3)
            	$menu.css("background","#50bdc6");

            else if(index==1 && nextIndex==4){
            	$menu.css("background","#fff");
            	if($secondRow.first().height()!=100)
            		$secondRow.animate({height: "100"},800);
            }
            else if(nextIndex==4){
            	$menu.css("background","#fff");
            	if($secondRow.first().height()!=100)
            		$secondRow.animate({height: "100"},600);
            }
            else if(nextIndex==5)
            	$menu.css("background","#50bdc6");
            else if(nextIndex==6)
            	$menu.css("background","#fff");

            
        },
        //menu:'#anchor-menu',
       //anchors:['firstPage', 'secondPage', 'thirdPage','fourthPage','fifthPage','sixthPage'],
        navigation:true
    });


    $(".job-seek").click(function (){
        $.fn.fullpage.moveTo(2);
    });
    $(".company-seek").click(function (){
  	  $.fn.fullpage.moveTo(4);
    });
   	$(".contact-seek").click(function (){
  	  $.fn.fullpage.moveTo(6);
    });

    $(".t-help__icon").css("height",3);

    $(".t-modal-caller").click(function (e){
        popupBanner();
        e.stopPropagation();
    });
    $(document).click(function(e) {
        if($modal.hasClass('-show')){
            $modal.animate({"opacity":"0"},500,function(){$modal.removeClass('-show')});
            $blur.removeClass('-show');
        }
    });
    $modal.click(function(e) {
        e.stopPropagation();
    });

   

   resizeToolbar();
 

});



 
	var toolbar=$('.t-toolbar');
	var toolbarMenu=$('.t-toolbar-menu');
	var toolbarLogo=$('.t-toolbar-logo');

	$(window).resize(function() {
		resizeToolbar();
	});
	
	function resizeToolbar(){
		if(toolbar.width()<=750) {
			if(!toolbarMenu.hasClass('-hidden')) {
				toolbarMenu.toggleClass('-hidden');
			}
			if(!toolbarLogo.hasClass('-center')) {
				toolbarLogo.toggleClass('-center');
			}
		}
		else {
			if(toolbarMenu.hasClass('-hidden')) {
				toolbarMenu.toggleClass('-hidden');
			}
			if(toolbarLogo.hasClass('-center')) {
				toolbarLogo.toggleClass('-center');
			}
		}
	}

    var $modal=$('.t-modal');
	var $blur=$('.t-blur-all');
    
    function popupBanner(){
        if($modal.hasClass('-show')){
            
            $modal.animate({"opacity":"0"},500,function(){$modal.removeClass('-show')});
            $blur.removeClass('-show');
        }
        else {
            $blur.addClass('-show');
            $modal.css('opacity','0');
            $modal.addClass('-show')
            $modal.animate({"opacity":"1"},500);
        }

    }
			



			function dropdown(el) {
				this.dd = el;
				this.placeholder = this.dd.children('span');
				this.opts = this.dd.find('ul.t-dropdown > li');
				this.val = '';
				this.index = -1;
				this.initEvents();
			}
			dropdown.prototype = {
				initEvents : function() {
					var obj = this;

					obj.dd.on('click', function(event){
						$(this).toggleClass('active');
						return false;
					});
					obj.opts.on('click',function(){

						var opt = $(this);
						obj.val = opt.text();
						obj.index = opt.index();
						obj.placeholder.text(obj.val);
					});
				},
				getValue : function() {
					return this.val;
				},
				getIndex : function() {
					return this.index;
				}
			}

			$(function() {

				var dd1 = new dropdown( $('#dd1') );
				var dd2 = new dropdown( $('#dd2') );
				var dd3 = new dropdown( $('#dd3') );

				$(document).click(function() {
					// all t-dropdowns
					$('.t-dropdown-wrapper').removeClass('active');
				});

			});





</script>

app/views/users/new.html.erb
<div class="t-block">
  <div class="t-middle">
<div class="t-register-card">
  <div class="t-register-form">
    <%= form_for(@user) do |f| %>
     <%= render 'shared/error_messages' %>
      <%= f.text_field :name, class: 't-input'%>
      <%= f.text_field :country, class: 't-input'%>
      <%= f.text_field :city, class: 't-input'%>
      <%= f.text_field :email, class: 't-input' %>
      <%= f.password_field :password, class: 't-input' %>
      <%= f.password_field :password_confirmation, class: 't-input' %>
      <%= submit_tag "Create my account", class: "t-submit" %>
      <% end %>
  </div>

  <div class="t-register-def">
    <div class="t-register-text">Create account in 60 seconds and start your career path.</div>
    <%= image_tag("register.png", :alt => "logo",:class => "t-register-picture") %>
    <% if @user.errors.any? %>
    <% if @user.errors.include?(:name) %>
      <div class="t-error -name">x</div>
    <% end%>
    <% if @user.errors.include?(:country) %>
      <div class="t-error -country">x</div>
    <% end %>
    <% if @user.errors.include?(:city) %>
      <div class="t-error -city">x</div>
    <% end %>
    <% if@user.errors.include?(:email) %>
       <div class="t-error -mail">x</div>
    <% end %>
    <% if@user.errors.include?(:password) %>
       <div class="t-error -pass">x</div>
    <% end %>
    <% if@user.errors.include?(:password_confirmation) %>
      <div class="t-error -confirm">x</div>
    <% end %>
    <% end %>
  </div>
</div>
</div>
</div>





<script>
$(document).ready(function() {
    var id=["#user_name","#user_email","#user_password","#user_password_confirmation",'#user_city','#user_country'];
    var value=["Full Name","Email","Password","Repeat password","City","Country"];

    for(i=0;i<6;i++) {
      $(id[i]).attr("placeholder", value[i]);
    }

});
</script>

app/views/users/show.html.erb
<div class="t-main-container">
	<div class="t-middle">
		<div>
			<div class="t-register-card">
				<%= image_tag("counter.png", :alt => "logo",:class => "t-counter") %>
				<div class="t-counter-text">Come back in</div>
				<div class='t-clock' data-countdown-until="<%= 10.days.from_now %>"></div>
				<%= link_to "Back to main page", root_path, {:class=>"t-card-button -left"} %>
				<%= link_to "Recent news",  "https://www.facebook.com/hireyoung/", {:class=>"t-card-button -right"} %>
			</div>
		</div>
	</div>
</div>


<script>





$(document).ready(function(){
	liftoffTime=new Date(2015, 12-1, 15);
  $('.t-clock').countdown({until: liftoffTime, format: 'DHM',layout:'<a class="t-clock-digit">{d<}{dn}</a> <a class="t-clock-word">{dl} {d>}</a> <a class="t-clock-digit">{hn}</a> <a class="t-clock-word">{hl}</a> <a class="t-clock-digit">{mn}</a> <a class="t-clock-word">{ml}</a>',labels:["year","month","week","days","hours","minutes","second"]});
});
</script>